### PR TITLE
recipe/CEN-9907 coordinate converter

### PR DESCRIPTION
**Pull request by strikeone88**
Recipe cooked.

### CODE REVIEW

**Review by gordonwade — CHANGES_REQUESTED** [review]
Hey @strikeone88 , our relative coordinates are on a 0 - 100 scale ([see docs](https://docs.centaurlabs.com/docs/wkt-format)). This looks like it is off by a factor of 100 (providing values 0-1 instead).

**Comment by strikeone88** [comment]
Done! I have added the scale by 100 I forgot. :)

**Review by gordonwade — APPROVED** [review]

**Comment by fayyazul-centaurlabs** [comment]
it looks like the os and json imports are unused, let's get rid of them.

**Comment by fayyazul-centaurlabs** [comment]
also this repo has a pre-commit config to strip metadata out of jupyter notebooks. Can you install and run pre-commit?

**Comment by fayyazul-centaurlabs** [comment]
and lastly you might want to update the example in the last cell:
```
wkt_string = 'POLYGON ((0 50, 0 100, 100 100, 100 50, 0 50))'
```

**Review by fayyazul-centaurlabs — CHANGES_REQUESTED** [review]
Otherwise this recipe looks great. Please run pre-commit on the notebook and I'll approve

**Comment by strikeone88** [comment]
Done! Please review.

**Review by fayyazul-centaurlabs — APPROVED** [review]
Great work!

**Pull request merged**
