### PR TITLE
CEN-6949 : DICOM to image

### PR DESCRIPTION
**Pull request by strikeone88**

### CODE REVIEW

**Review by gordonwade — COMMENTED** [review]
Hey @strikeone88 , this looks like a good start!

The code in our existing codebases also covers modality LUT / VOI LUT transformations as well as window level transformations if one is provided in the header. I think these elements should probably be incorporated here as well.

**Comment by fayyazul-centaurlabs** [comment]
Hey @gordonwade , I actually disagree that we should include transformations. Recipes should be simple and focus on one aspect. This recipe looks like it's doing too much. Dicom transformations should be put in a separate recipe. This recipe should focus solely on just writing an image given a dicom file.

**Comment by strikeone88** [comment]
Question for @fayyazul-centaurlabs can I include links within this recipe to the other recipes of transformations? In the README so that people can easily find those? Or do we link them in the main repo's README?

**Comment by gordonwade** [comment]
> Hey @gordonwade , I actually disagree that we should include transformations. Recipes should be simple and focus on one aspect. This recipe looks like it's doing too much. Dicom transformations should be put in a separate recipe. This recipe should focus solely on just writing an image given a dicom file.

Hey @fayyazul-centaurlabs , thanks for weighing in. I understand the desire to keep things simple, but I'm not 100% convinced on this. The main questions I have are:

- Is there utility in having a recipe that simply directly converts DICOM pixel values to images?
  - I'm a bit skeptical of the value here since it seems like Modality LUT or Rescale should always be performed prior to display. I do see slightly more of a case for separating VOI and custom window level transformations.
- If we split this into two recipes, how hard would it be for our users to combine them?
  - It's best if recipes can be connected end-to-end. In this case, we might have one recipe that accepts a DICOM file and produces a PNG/JPG and another recipe that accepts a DICOM file and produces a modified pixel array. In order to combine these, the customers would have to basically reconstruct the recipe we have here.
- Is the recipe as-is overly complicated?
  - This is subjective, but the current recipe only has 7 cells and seems fairly straightforward.

Ultimately, I think keeping recipes simple is a good thing but thinking about the customer use case is also important. It may not make a ton of sense to separate recipes that are going to end up being used together in the vast majority of cases anyway.

I am open to being convinced on these points, so please let me know what you think!

**Review by fayyazul-centaurlabs — CHANGES_REQUESTED** [review]
```python
from os import path
```
let's use `Path` from `pathlib`. Modern python favors `pathlib` over `os.path`.
On a similar note, we generally follow pep8 guidelines which call for snake_case variable names instead of camelCase.

---

```
rescaleSlope = ds.get("RescaleSlope") or 1.0
rescaleIntercept = ds.get("RescaleIntercept") or 0.0
pixel_array = pixel_array * rescaleSlope + rescaleIntercept
```
[apply_modality_lut](https://github.com/pydicom/pydicom/blob/41d9307bc025b7258e91d0bc52ea2f65fdbfb99a/src/pydicom/pixel_data_handlers/util.py#L251) does a bit more than just apply the rescale so let's still use that function if "ModalityLUTSequence" is present in the dicom. Maybe do 
```python
if "ModalityLutSequence" in ds or ("RescaleSlope" in ds and "RescaleIntercept" in ds):
...
```

---

```python
pixel_array = pixel_array.astype(pixel_array.dtype.name.replace("float", "int"))
```
we should just do `pixel_array.astype(int)` or `pixel_array.astype(np.int64)` here. 

---

```python
elif imageType == "YBR_FULL" or imageType == "YBR_FULL_422":
    pixel_array = convert_color_space(pixel_array, imageType, "RGB")
```
convert_color_space also handles RGB so you can just apply it for all three non-monochrome types. You can use `elif image_type in ("RGB", "YBR_FULL", "YBR_FULL_422")`
 

```python
if imageType.startswith("YBR") or imageType == "RGB":
    pixel_array = cv2.cvtColor(pixel_array.astype("float32"), cv2.COLOR_RGB2BGR)
```
not sure this is needed

---

```python
hasattr(ds, "NumberOfFrames") and ds.NumberOfFrames > 1
``` 
can simplify to `ds.get("NumberOfFrames", 1) > 1`

**Comment by strikeone88** [comment]
Hey @fayyazul-centaurlabs I patched according to your latest comments. And about the BGR conversion, that one is required when using YBR and RGB because the output for CV2 must be in BGR format or the colors will be flipped.

Current notebook tested against all example images, and all working as expected. 👍🏽

**Review by fayyazul-centaurlabs — APPROVED** [review]
great work! 

also my bad, it should have been `ModalityLUTSequence`, apparently the casing does matter and pydicom throws a warning if it's `Lut` instead.

btw you don't need to make int a string in astype. you can use the built in type as is. i.e., `astype(int)` rather than `astype("int")`

just make the `Lut` -> `LUT` change and you can go ahead and merge.

**Pull request merged**
